In [3]:
import torch 

# Exploring pytorch 

In [6]:
randint = torch.randint(-100, 100, (6,))     # generate 1D tensor of 6 element between -100 to 100
randint

tensor([ 30,  68,  16, -89,  60,  46])

In [8]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [9]:
tensor.shape

torch.Size([3, 2])

In [12]:
zeros= torch.zeros(3,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
ones = torch.ones(3,1)
ones

tensor([[1.],
        [1.],
        [1.]])

In [15]:
input = torch.empty(2,3)
input

tensor([[1.0194e-38, 4.6838e-39, 4.5000e-39],
        [9.9184e-39, 9.0000e-39, 9.3673e-39]])

In [17]:
arange = torch.arange(10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
linspace = torch.linspace(3,10, steps=5)                     # generate linearly spaced number 
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [19]:
logspace = torch.logspace(start = -10, end=-10, steps=5)       #generate logarithimcally spaced number
logspace

tensor([1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10])

In [21]:
eye = torch.eye(5)                          # 5*5 reducde row echelon matrix
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
a = torch.empty((2,3) , dtype= torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
# 

In [26]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'         # check the availability of gpu
device

'cuda'

In [27]:
# different between gpu and cpu
import numpy as np
import time


In [33]:
%%time
start_time = time.time()

# matrix operations
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [34]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)                         # uses to('cuda') if gpu is available
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)                         # else uses to('cpu')  if gpu is not availabel

np_rand1 = torch.rand(100, 100, 100, 100)                                       # only cpu
np_rand2 = torch.rand(100, 100, 100, 100)

# for gpu : parallel processing 
start_time = time.time()
rand = (torch_rand1 @ torch_rand2)                                             # vectorization means gpu use
end_time = time.time()                                                         
elapsed_time = end_time - start_time                                       
print(f"{elapsed_time:.8f}")                                                   # time taken by gpu

# for cpu : seqence processing 
start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)                                        # sequential processing 
end_time = time.time()

elapsed_time = end_time - start_time                                          # time taken by cpu
print(f"{elapsed_time:.8f}")

0.02288747
0.07646346
CPU times: total: 1.77 s
Wall time: 1.86 s
